apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::654848625567:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7H7MVZWHOWJ1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::654848625567:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T10:52:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1653"
  uid: 390face4-14a8-4740-99b9-32cce5ff1786
